x-common: &common
  init: true
  network_mode: host
  restart: always
  logging:
    driver: "json-file"
    options:
      max-file: "5"
      max-size: "10m"
services:
  phenix:
    build:
      context: ../
      dockerfile: docker/Dockerfile
      args:
        MM_MIN_REV: 9f867b3
        PHENIX_WEB_AUTH: disabled
    command:
    - phenix
    - ui
    - --hostname-suffixes=-minimega,-phenix
    - --minimega-console
    image: phenix
    container_name: phenix
    privileged: true
    pid: host
    <<: *common
    volumes:
      - /dev:/dev
      - /etc/localtime:/etc/localtime:ro
      - /var/log/phenix:/var/log/phenix
      - /etc/phenix:/etc/phenix
      - /var/run/netns:/var/run/netns:shared
      - /phenix:/phenix:shared
      - ./tmp/minimega:/tmp/minimega
      - ./tmp/phenix:/tmp/phenix

    depends_on:
      - minimega
    healthcheck:
      test: phenix version
  minimega:
    build:
      context: .
      dockerfile: Dockerfile.minimega
      args:
        MM_REV: 9f867b3
    image: minimega
    container_name: minimega
    privileged: true
    <<: *common
    volumes:
      - /dev:/dev
      - /lib/modules:/lib/modules:ro
      - /etc/localtime:/etc/localtime:ro
      - /var/log/phenix:/var/log/phenix
      - /var/run/netns:/var/run/netns:shared
      - /phenix:/phenix:shared
      - ./tmp/minimega:/tmp/minimega
      - ./tmp/phenix:/tmp/phenix
      # Mount your fork of sceptre-phenix-apps
      # At runtime after making changes: docker exec -it phenix python3 -m pip install /opt/oss-phenix-apps
      # Syntax: <path-to-fork>:/opt/oss-phenix-apps
      - /home/ubuntu/sceptre-phenix-apps-reyna/src/python:/opt/oss-phenix-apps
    healthcheck:
      test: mm version
    environment:
      MM_FILEPATH: /phenix/images
      MM_LOGFILE: /var/log/phenix/minimega.log
      MM_LOGLEVEL: info
